const d = (n) => new Date(Date.now() + n * 864e5 - 36e5).toISOString();

const elig = (a) => [
  { label: 'African woman in technology', met: true },
  { label: 'Student or recent graduate', met: true },
  { label: 'Passion for the field', met: true },
  { label: '3+ months availability', met: a },
];

export const opportunities = [
  {
    id: 'sca',
    title: 'SCA Contributhon Fellowship 2026',
    org: 'She Code Africa',
    category: 'Fellowship',
    deadline: d(8),
    location: 'Remote',
    match: 96,
    summary:
      'A six-week open source fellowship empowering African women to contribute to OSS projects with mentorship and stipend support.',
    description:
      'A six-week open source contribution fellowship empowering African women to contribute to impactful OSS projects with mentorship and stipend support.',
    eligibility: elig(false),
    benefits: [
      '$500 monthly stipend',
      '1:1 Mentorship',
      'Certificate of completion',
      'SCA Community access',
    ],
    url: 'https://shecodeafrica.org',
  },
  {
    id: 'wtm',
    title: 'Women Techmakers Scholars Program',
    org: 'Google Developers',
    category: 'Scholarship',
    deadline: d(14),
    location: 'Global',
    match: 89,
    summary: 'Scholarship and mentorship for women pursuing careers in computing.',
    description: 'Funding, mentorship and community for women in computing.',
    eligibility: elig(true),
    benefits: ['Scholarship award', 'Mentorship', 'Google community'],
    url: 'https://developers.google.com/womentechmakers',
  },
  {
    id: 'alx',
    title: 'ALX Software Engineering Program',
    org: 'ALX Africa',
    category: 'Bootcamp',
    deadline: d(21),
    location: 'Remote',
    match: 82,
    summary: 'Intensive software engineering training with peer learning.',
    description: 'A structured software engineering programme with peer learning.',
    eligibility: elig(true),
    benefits: ['Full curriculum', 'Peer learning', 'Career support'],
    url: 'https://alxafrica.com',
  },
  {
    id: 'adc',
    title: 'ADC Africa Developer Centre Internship',
    org: 'Microsoft',
    category: 'Internship',
    deadline: d(0.1),
    location: 'Lagos, NG',
    match: 78,
    summary: 'Hands-on internship at the Africa Development Centre.',
    description: 'Work alongside engineers on production software.',
    eligibility: elig(true),
    benefits: ['Paid internship', 'Mentorship'],
    url: 'https://microsoft.com',
  },
  {
    id: 'zindi',
    title: 'Africa Health AI Hackathon',
    org: 'Zindi Africa',
    category: 'Hackathon',
    deadline: d(30),
    location: 'Remote',
    match: 91,
    summary: 'Build AI solutions for health challenges across Africa.',
    description: 'Team hackathon on health data.',
    eligibility: elig(true),
    benefits: ['Cash prizes', 'Recruiter access'],
    url: 'https://zindi.africa',
  },
];

export const communities = [
  {
    id: 'sca',
    name: 'She Code Africa',
    members: '24K',
    events: 3,
    desc: 'The largest community for African women in tech',
  },
  {
    id: 'wtm',
    name: 'Women Techmakers',
    members: '12K',
    events: 2,
    desc: "Google's program for women in technology",
  },
  {
    id: 'andela',
    name: 'Andela Community',
    members: '8K',
    events: 1,
    desc: 'World-class African tech talent network',
  },
  {
    id: 'gdsc',
    name: 'GDSC Africa',
    members: '30K',
    events: 5,
    desc: 'Google Developer Student Clubs across Africa',
  },
  {
    id: 'wiai',
    name: 'Women in AI Africa',
    members: '8K',
    events: 2,
    desc: 'Advancing AI education for African women',
  },
  {
    id: 'afro',
    name: 'Afrolynk Community',
    members: '4K',
    events: 1,
    desc: 'Pan-African tech startup ecosystem',
  },
];
